export * from './language-prisma.service';
export * from './platform-prisma.service';
export * from './tone-prisma.service';
export * from './industry-prisma.service';
export * from './company-size-prisma.service';
export * from './company-type-prisma.service';
export * from './target-prisma.service';
export * from './client-company-prisma.service';
export * from './content-type-prisma.service';
